#define MAJOR_VERSION	0
#define MINOR_VERSION	3
#define MICRO_VERSION	5
#define BUILD_NUMBER	61

#define QUOTE_(x)		#x
#define QUOTE(x)		QUOTE_(x)

#define VERSION_STRING	QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION)
#define VERSION_STRING_W	_T(QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION))
#define BUILD_NUMBER_A	_T(QUOTE(BUILD_NUMBER))

#define BUILD_DATE		21st December 2021
#define BUILD_DATE_STRING	_T(QUOTE(BUILD_DATE))
