#define MAJOR_VERSION	0
#define MINOR_VERSION	8
#define MICRO_VERSION	0
#define BUILD_NUMBER	_T("282")
#define YEAR_NUMBER		_T("2022")
#define BUILD_LAB		_T("SE_dev-vm")

#define QUOTE_(x)		#x
#define QUOTE(x)		QUOTE_(x)

#define VERSION_STRING	QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION)
#define VERSION_STRING_W	_T(QUOTE(MAJOR_VERSION.MINOR_VERSION.MICRO_VERSION))
#define BUILD_STRING	_T(QUOTE(MAJOR_VERSION.MINOR_VERSION.BUILD_STRING.MICRO_VERSION.BUILD_LAB.BUILD_TIME))

#ifdef NDEBUG
#define DEBUG_STRING	_T("")
#else
#define DEBUG_STRING	_T("Debug")
#endif

#define BUILD_DATE		_T("23rd May 2022")
#define BUILD_TIME		_T("220523-1951")